name: Mirror to GitLab

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository
        run: |
          git clone --mirror https://github.com/${{ github.repository }}.git repo.git
          cd repo.git

          git push --mirror https://${{ secrets.GH_SCCS_FORWARD_USER }}:${{ secrets.GH_SCCS_FORWARD_TOKEN_T1 }}@gitlab.com/royoelen/single-cell-container-server.git
